version: "3.7"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - ../Saphira/:/var/www/project/:cached
    ports:
      - 10302:80
    networks:
      - symfony
    depends_on:
      - saphira
    links:
      - saphira
  saphira:
    build:
      context: .
      dockerfile: Dockerfile-saphira
    environment: # You can use this section to set environment variables. But you can also use the .env file.
      - DATABASE_URL=mysql://root:root@db/docker_sf
    volumes:
      - ../Saphira/:/var/www/project/:cached # This should be the same for NGINX.
    networks:
      - symfony
  db: #address
    image: mariadb:10.2.29
    ports:
      - "3317:3306" #patern: from-within
    environment:
      - MYSQL_DATABASE=docker_sf
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysqldata:/var/lib/mysql
      - ./build/db/:/docker-entrypoint-initdb.d/
    networks:
      - symfony
networks:
  symfony: