version: "3.9"
services:
  nginx:
    build:
      context: ./build/
      dockerfile: Dockerfile-nginx
    volumes:
      - ../Saphira/:/var/www/project/:cached
    ports:
      - 80:80
    networks:
      - main_net
    depends_on:
      - saphira
      - brisingr

  saphira:
    build:
      context: ./build/
      dockerfile: Dockerfile-saphira
    volumes:
      - ../Saphira/:/var/www/project/:cached # This should be the same for NGINX.
    networks:
      - main_net
      - apps_net
    ports:
      - "9000:9000"

  brisingr:
    build:
      context: ./build/
      dockerfile: Dockerfile-brisingr
    volumes:
      - ../Brisingr/:/var/www/project/:cached # This should be the same for NGINX.
    networks:
      - main_net
      - apps_net
      - mysql_net
    ports:
      - "9001:9001"

  mysql_db: #address
    image: mariadb:10.2.29
    container_name: mysql_db
    ports:
      - "3306:3306" #patern: from-within
    environment:
      - MYSQL_DATABASE=project_m
      - MYSQL_USER=saphira_app
      - MYSQL_PASSWORD=YVqHxkPbrajF9C
      - MYSQL_ROOT_PASSWORD=MwIwhXLMXjzWRvWktgec
    volumes:
      - ./mysqldata:/var/lib/mysql
      - ./build/db/init/:/docker-entrypoint-initdb.d/
    networks:
      - mysql_net

networks:
  main_net:
    driver: bridge
  mysql_net:
    driver: bridge
  apps_net:
    driver: bridge